kind: pipeline
name: default

steps:
- name: scp
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: host
    port:
      from_secret: port
    username:
      from_secret: username
    password:
      from_secret: password
    target: 
      from_secret: target
    source: 
      from_secret: source
    when:
      branch: master