kind: pipeline
name: default

steps:
- name: scp
  image: appleboy/drone-scp
  settings:
    host: $host
    username: $username
    password: $password
    port: $port
    target: /data/wwwroot/www.lotteryjs.com
    source: ./docs
    when:
      branch: master