kind: pipeline
name: default

steps:
- name: scp
  image: appleboy/drone-scp
  settings:
    host: ${SCP_HOST}
    port: ${SCP_USERNAME}
    username: ${SCP_PASSWORD}
    password: ${SCP_PORT}
    secrets: [ SCP_HOST, SCP_USERNAME, SCP_PASSWORD, SCP_PORT ]
    target: /data/wwwroot/www.lotteryjs.com
    source: ./docs
    when:
      branch: master